dist: trusty
sudo: false

language: java

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  # - oraclejdk9


install:
    - export main_repo_branch=$TRAVIS_BRANCH
    - echo $main_repo_branch
    - if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" && ${main_repo_branch} != "experimental" ]]; then main_repo_branch=development ; fi
    
    - pwd
    - cd ..
    - git clone https://github.com/LEMS/jLEMS.git
    - cd jLEMS
    - git checkout $main_repo_branch
    - mvn install
    - cd ../LEMS
    - pwd
    - ls -alt
    
    - cd docgeneration
    - ant

