# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:  [ master, development, experimental, osb* ]
  pull_request:
    branches:  [ master, development, experimental, osb* ]

jobs:
  build_and_test:

    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        java: [ '8', '11', '16', '17' ]
        runs-on: [ubuntu-latest, macos-11, windows-latest]

    name: Test on Java ${{ matrix.Java }} on ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.Java }}
      uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.Java }}
        distribution: 'adopt'
        
    - name: Tests, non Win
      if: ${{ matrix.runs-on != 'windows-latest' }}
      run: |
        
        export main_repo_branch=${{env.main_repo_branch}}
        if [[ ${main_repo_branch} != "master" && ${main_repo_branch} != "development" && ${main_repo_branch} != "experimental" && ${main_repo_branch} != *"osb"* ]]; then main_repo_branch=development ; fi
        echo Using branch $main_repo_branch
        
        
        git clone https://github.com/LEMS/jLEMS.git
        cd jLEMS
        git checkout $main_repo_branch
        mvn install
        mvn dependency:tree
        cd ../examples
        
        pwd
        ls -alt
        ../jLEMS/lems example1.xml -nogui
        ../jLEMS/lems example2.xml -nogui
        ../jLEMS/lems example3.xml -nogui
        ../jLEMS/lems example4.xml -nogui
        ../jLEMS/lems example5.xml -nogui
        ../jLEMS/lems example6.xml -nogui
        ../jLEMS/lems example7.xml -nogui
        ../jLEMS/lems example8.xml -nogui

        
    - name: Further tests, Windows
      if: ${{ matrix.runs-on == 'windows-latest' }}
      run: |
        pwd
        dir
        mvn dependency:tree
        
        ./lems.bat src\test\resources\example1.xml -nogui
        ./lems.bat src\test\resources\eexample2.xml -nogui
        ./lems.bat src\test\resources\example3.xml -nogui
        ./lems.bat src\test\resources\example4.xml -nogui
        ./lems.bat src\test\resources\example5.xml -nogui
        ./lems.bat src\test\resources\example6.xml -nogui
        ./lems.bat src\test\resources\example7.xml -nogui
        ./lems.bat src\test\resources\example8.xml -nogui
