
name: Publish LEMS documentation

on:
  push:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: nelonoel/branch-name@v1.0.1

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        java-package: jdk
        distribution: 'temurin'


    - name: Install GH import
      run: |
        python -m pip install --upgrade pip
        pip install ghp-import

    - name: Build docs
      run: |
        cd ..
        git clone https://github.com/LEMS/jLEMS.git
        cd jLEMS
        git checkout development
        mvn install
        cd ../LEMS/docgeneration
        ant -p
        ant 
        ls -alt html

    - name: Publish documentation on GH pages
      run: |
        echo "Testing in $(pwd)"
        ghp-import -f -m "Regenerate documentation" -b gh-pages -n -p docgeneration/html/

